language: java
script: mvn test
before_script:
  - chmod a+x /home/travis/build/Fissionworks/ddt-utils/target/test-classes/exitCodeFortyTwo.sh
  - chmod a+x /home/travis/build/Fissionworks/ddt-utils/target/test-classes/sleepTwoSeconds.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
jdk:
  - oraclejdk8
